"""init

Revision ID: 825ac4ff9b0e
Revises: 
Create Date: 2026-05-16 22:46:29.781331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '825ac4ff9b0e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_state',
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active_incidents', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('state_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('city')
    )
    op.create_table('incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('crisis_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evidence_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('affected_zones', postgresql.ARRAY(sa.TEXT()), nullable=True),
    sa.Column('signal_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('state_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('route_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_path', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rerouted_path', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('signal_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('crisis_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_hint', sa.Float(), nullable=False),
    sa.Column('verification_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cross_referenced_with', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('raw_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('authority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("""
    CREATE OR REPLACE FUNCTION notify_incident_change()
    RETURNS TRIGGER AS $$
    BEGIN
      PERFORM pg_notify(
        'incidents_channel',
        json_build_object(
          'event',       TG_OP,
          'incident_id', NEW.id::text,
          'city',        NEW.city,
          'severity',    NEW.severity,
          'status',      NEW.status
        )::text
      );
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)
    op.execute("""
    CREATE TRIGGER incidents_notify_trigger
      AFTER INSERT OR UPDATE ON incidents
      FOR EACH ROW EXECUTE FUNCTION notify_incident_change();
    """)
    
    op.execute("""
    CREATE OR REPLACE FUNCTION update_active_incidents()
    RETURNS TRIGGER AS $$
    BEGIN
      UPDATE city_state 
      SET active_incidents = (
        SELECT count(*) FROM incidents 
        WHERE city = COALESCE(NEW.city, OLD.city) 
        AND status NOT IN ('resolved', 'feed_only')
      )
      WHERE city = COALESCE(NEW.city, OLD.city);
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)
    op.execute("""
    CREATE TRIGGER incidents_active_count_trigger
      AFTER INSERT OR UPDATE OR DELETE ON incidents
      FOR EACH ROW EXECUTE FUNCTION update_active_incidents();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS incidents_active_count_trigger ON incidents;")
    op.execute("DROP FUNCTION IF EXISTS update_active_incidents();")
    op.execute("DROP TRIGGER IF EXISTS incidents_notify_trigger ON incidents;")
    op.execute("DROP FUNCTION IF EXISTS notify_incident_change();")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    op.drop_table('actions')
    op.drop_table('signals')
    op.drop_table('routes')
    op.drop_table('incidents')
    op.drop_table('city_state')
    # ### end Alembic commands ###
